#!/usr/bin/env bash
# Script that configures nginx server to redirect to another server

# Update package list
sudo apt-get update

# Install Nginx (if not already installed)
sudo apt-get install -y nginx

# Create a simple "Hello World!" HTML page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Check if the Nginx configuration file is at /etc/nginx/sites-available/default
nginx_config_file="/etc/nginx/sites-available/default"
if [ -f "$nginx_config_file" ]; then
    # Configure Nginx to redirect
    string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/davykoch permanent;"
    sudo sed -i "s/server_name _;/$string_for_replacement/" "$nginx_config_file"

    # Create a symbolic link to enable the site
    sudo ln -s "$nginx_config_file" "/etc/nginx/sites-enabled/"

    # Remove default configuration (if needed)
    sudo rm -f /etc/nginx/sites-enabled/default

    # Restart Nginx using the service command
    sudo service nginx restart
else
    echo "Nginx configuration file not found at $nginx_config_file"
fi
