#!/usr/bin/env bash
# Bash script that displays listening ports:
# That only shows listening sockets
# That shows the PID and name of the program to which each socket belongs

# Display listening TCP ports
ss -tln | awk 

# Display listening UDP ports
ss -uln | awk 

echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"

# Display listening UNIX domain sockets
ss -lx | awk 
