#!/usr/bin/env bash
# Manages the script manage_my_process.
#   When passed the argument `start`:
#     1. Starts manage_my_process
#     2. Creates a file containing its PID in /var/run/my_process.pid
#     3. Displays "manage_my_process started"
#   When passed the argument `stop`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Displays "manage_my_process stopped"
#   When passed the argument `restart`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Starts manage_my_process
#     4. Creates a file containing its PID in /var/run/my_process.pid
#     5. Displays "manage_my_process restarted"
#   If any other or no arguments are passed, displays
#   "Usage: manage_my_process {start|stop|restart}"

pid_file="/var/run/my_process.pid"

start_process() {
  if [ -e "$pid_file" ]; then
    echo "manage_my_process is already running"
  else
    ./manage_my_process &   # Start the process in the background
    echo $! > "$pid_file"  # Save the process ID to the PID file
    sleep 2  # Wait for the process to initialize
    echo "manage_my_process started"
  fi
}

stop_process() {
  if [ -e "$pid_file" ]; then
    pkill -P "$(cat "$pid_file")"  # Send SIGTERM to the process group
    wait "$(cat "$pid_file")"  # Wait for the process to finish
    rm -f "$pid_file"  # Remove the PID file
    echo "manage_my_process stopped"
  else
    echo "manage_my_process is not running"
    exit 1
  fi
}

restart_process() {
  stop_process
  start_process
  echo "manage_my_process restarted"
}

case "$1" in
  start)
    start_process
    ;;
  stop)
    stop_process
    ;;
  restart)
    restart_process
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
