#!/usr/bin/env bash
# Manages the script manage_my_process.
#   When passed the argument `start`:
#     1. Starts manage_my_process
#     2. Creates a file containing its PID in /var/run/my_process.pid
#     3. Displays "manage_my_process started"
#   When passed the argument `stop`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Displays "manage_my_process stopped"
#   When passed the argument `restart`:
#     1. Stops manage_my_process if running
#     2. Deletes the file /var/run/my_process.pid
#     3. Starts manage_my_process
#     4. Creates a file containing its PID in /var/run/my_process.pid
#     5. Displays "manage_my_process restarted"
#   If any other or no arguments are passed, displays
#   "Usage: manage_my_process {start|stop|restart}"

pid_file="/var/run/my_process.pid"

start_process() {
  if [ -e "$pid_file" ]; then
    echo "manage_my_process is already running. Use 'restart' to restart it."
  else
    ./manage_my_process &
    echo $! > "$pid_file"
    echo "manage_my_process started"
  fi
}

stop_process() {
  if [ -e "$pid_file" ]; then
    kill "$(cat "$pid_file")" && wait "$(cat "$pid_file")"
    rm -f "$pid_file"
    echo "manage_my_process stopped"
  else
    echo "manage_my_process is not running."
  fi
}

restart_process() {
  stop_process
  start_process
  echo "manage_my_process restarted"
}

case "$1" in
  start)
    start_process
    ;;
  stop)
    stop_process
    ;;
  restart)
    restart_process
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
