#!/usr/bin/env bash
# Bash script that groups visitors by IP and HTTP status code and displays the data

log_file="apache-access.log"

# Use awk to extract and format the information
awk '{print $1 " " $9}' "$log_file" | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'