#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

# Backup the original /etc/hosts file
cp /etc/hosts /etc/hosts_backup

# Update localhost entry to 127.0.0.2
sed -i '/localhost/ s/127.*$/127.0.0.2/' /etc/hosts

# Update facebook.com entry to 8.8.8.8
echo "8.8.8.8 facebook.com" >> /etc/hosts
