#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it’s executed on

# Use ip to get network interface information and grep for IPv4 addresses
ifconfig | grep -oE "\b(addr:)?([0-9]*\.){3}[0-9]*\b"
