#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it’s executed on

# Use ip to get network interface information and grep for IPv4 addresses
ip addr | awk '/inet / {print $2}' | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b"
